global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0  # Increased for better dynamic obstacle handling
  publish_frequency: 1.0
  static_map: true
  transform_tolerance: 0.5
  
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # TEB-specific global costmap parameters
  resolution: 0.05
  width: 50.0
  height: 50.0