local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0  # Higher frequency for dynamic obstacles
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 6.0  # Larger window for TEB planning
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5
  
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # TEB-specific local costmap parameters
  obstacle_layer:
    track_unknown_space: true
    combination_method: 1