# local_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 2.0
#   publish_frequency: 1.0
 
#   rolling_window: true
#   width: 5
#   height: 5
#   resolution: 0.03
#   transform_tolerance: 0.5
  
#   plugins:
#    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
#    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}

#NEW
local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 3.0
 
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.03
  transform_tolerance: 0.5
  
  plugins:
    - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}